### ISSUE TITLE
gif to apng will be broken

### ISSUE THREAD

**Issue by zhangguanzhang** [kettek/apngr#3]
![test](https://user-images.githubusercontent.com/18641678/147579904-83126898-b01a-48ae-b655-d85caf02d2bd.gif)
could use this gif to test run

**Comment by kettek** [comment]
It seems this is due to APNG/PNG having a single palettes table, but GIF allowing a palettes table per frame.

If I'm correct, I will have to analyze all GIF frames, collect the unique palettes and their indices for each, create a unified palette, then remap the old frames' palette references to the new global palette. This should potentially be hoisted up to the apng library, but I'll see about implementing it in apngr first.

**Comment by zhangguanzhang** [comment]
Thanks for the reply, I will wait for the update

**Comment by zhangguanzhang** [comment]
If you have completed the results, please be sure to remind me here

**Comment by kettek** [comment]
For sure, estimated for sometime this next week

**Comment by kettek** [comment]
Just an update -- I have it working for the most part, but there are still some issues.

![147579904-83126898-b01a-48ae-b655-d85caf02d2bd](https://user-images.githubusercontent.com/12402742/148747266-8864b3b0-116f-4278-aafe-1d57b983752f.png)
.

**Comment by kettek** [comment]
Simple error. I wasn't adjusting based on x/y offsets of frames. Seems to work well enough, but will add CLI options for controlling conversions first.
![147579904-83126898-b01a-48ae-b655-d85caf02d2bd](https://user-images.githubusercontent.com/12402742/148750463-45e06034-2e39-4da2-ba3d-4fa674f83407.png)

**Comment by zhangguanzhang** [comment]
😘Thank you very much for taking your personal time to solve this problem, but I don't see the repository code being committed

**Comment by kettek** [comment]
Try the latest master commit and let me know if it works fine for you. Will make an official release after more testing and CLI enhancements.

**Comment by zhangguanzhang** [comment]
![head](https://user-images.githubusercontent.com/18641678/148759919-c928ab9b-d26f-4fcd-b1a9-1d7d717e0fd0.gif)
this gif will be broken after the convert

**Comment by kettek** [comment]
Hmm, not certain, but golang's [color.Palette.Index()](https://pkg.go.dev/image/color#Palette.Index) call seems to not be returning a closest RGB value, but rather an aggregate RGBA value.

Also, to note, GIF supports 256 colors _per frame_, but PNG supports 256 colors _per image_. This seems to be a distinction with this image that PNG cannot support. However, we should able to at least get the closest color we can, which seems to be failing at the moment.

**Comment by kettek** [comment]
I believe we need to just convert GIF files into non-indexed PNG files, in the event we run into more than 256 palette entries. This should fix the problems with your Dr. Who GIF. I'll try to devise a way to first keep within the indexed color range, then switch to RGBA when it is not possible to maintain.

**Comment by zhangguanzhang** [comment]
Thank you very much for your help, I personally am not in a hurry for this problem, you can do it when you have extra spare time

**Comment by kettek** [comment]
Latest update seems to work. When the palette entry count exceeds 256, the output will become RGBA. I have added a CLI option to prevent this behavior if desired, but it then just uses golang's builtin closest color index matching which seems dubious.

![148759919-c928ab9b-d26f-4fcd-b1a9-1d7d717e0fd0](https://user-images.githubusercontent.com/12402742/148897464-4dc8b0b6-733c-478b-b973-3c7c2c5a282f.png)

**Comment by zhangguanzhang** [comment]
I test with some gifs, It works fine

**Comment by kettek** [comment]
Closed by f56bc9c2580828c904d4664376aaafd4eff35dc8 and released in [v1.1.0](https://github.com/kettek/apngr/releases/tag/v1.1.0).

Thank you for bringing this to my attention!
